version: "3.8"

services:
  astro_app:
    command: sh -c "cp -r /app/dist/client/. /app/static_assets/ && node /app/dist/server/entry.mjs"
    volumes:
      # Монтируем наш новый том в папку, куда Astro складывает
      # клиентские статические файлы.
      - astro_static:/app/static_assets
  nginx:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf/production.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /etc/letsencrypt/ssl-dhparams.pem:/etc/letsencrypt/ssl-dhparams.pem
      - astro_static:/var/www/html/static:ro
