version: "3.8"

services:
  astro_app:
    build: ./astro-app
    restart: always
    expose:
      - "443"

  nginx:
    image: nginx:1.25-alpine
    restart: always
    depends_on:
      - astro_app
